### ISSUE TITLE
Can't get SBMLReader.readSBMLFromFile to work from Python

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/libsbml#74]
This is me trying to get SBMLReader.readSBMLFromFile to work on Python:

```
$ ~/AppData/Local/Programs/Python/Python37/python.exe -m pip install python-libsbml
Collecting python-libsbml
  Downloading python_libsbml-5.18.0-cp37-cp37m-win_amd64.whl (7.1 MB)
     |████████████████████████████████| 7.1 MB 3.2 MB/s
Installing collected packages: python-libsbml
Successfully installed python-libsbml-5.18.0

Lucian@Hagencrum /cygdrive/c/Users/Lucian/Desktop/test_spyder
$ ~/AppData/Local/Programs/Python/Python37/python.exe
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsbml
>>> libsbml.SBMLReader.readSBMLFromFile("BIOMD0000000339.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python37\lib\site-packages\libsbml\__init__.py", line 2211, in re
adSBMLFromFile
    args_copy[1] = conditional_abspath(args[1])
IndexError: tuple index out of range
>>> libsbml.SBMLReader.readSBMLFromFile("BIOMD0000000339.xml", "")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucian\AppData\Local\Programs\Python\Python37\lib\site-packages\libsbml\__init__.py", line 2212, in re
adSBMLFromFile
    return _libsbml.SBMLReader_readSBML(*args_copy)
TypeError: in method 'SBMLReader_readSBML', argument 1 of type 'SBMLReader *'
>
```

Am I doing something wrong?  Is something broken?

(The same thing happens with 'readSBML'.)

**Comment by fbergmann** [comment]
You need to instantiate the reader first. And then you can call the method
on it. It is not a static method.

**Comment by luciansmith** [comment]
Ah, that makes more sense.  I also eventually figured out that I could call libsbml.readSBMLFromFile("file.xml") directly.  Thanks!
